security:
    password_hashers:
        App\Entity\Responsable: # On applique le hashage aux utilisateurs de type Responsable
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Responsable
                property: login  # Le champ utilisé pour identifier l'utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider  # On utilise le provider basé sur l'entité Responsable
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: accueil
                enable_csrf: false  # Désactiver CSRF dans la configuration du formulaire de login
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        # Pas de règle spécifique pour /inscription, donc elle est publique
