controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\HomeController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
