controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

reponsable:
    path: /responsable
    controller: App\Controller\ResponsableController::index

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index

compte:
    path: /compte
    controller: App\Controller\CompteController::index

commande:
    path: /commande
    controller: App\Controller\CommandeController::index

commande_other:
    path: /commande/other
    controller: App\Controller\CommandeController::other

produit:
    path: /produit
    controller: App\Controller\ProduitController::index

produit_new:
    path: /produit/new
    controller: App\Controller\ProduitController::new
    methods: [GET, POST]

# config/routes.yaml

update_en_ligne:
    path: /produit/{id}/update-en-ligne
    controller: App\Controller\ProduitController::updateEnLigne
    methods: POST

update_statut:
    path: /commande/{id}/update-statut
    controller: App\Controller\CommandeController::updateStatut
    methods: POST

add_categorie:
    path: /produit/new/add-categorie
    controller: App\Controller\AjaxController::addCategorie
    methods: POST

add_sous_categorie:
    path: /produit/new/add-sous_categorie
    controller: App\Controller\AjaxController::addSousCategorie
    methods: POST

add_taille:
    path: /produit/new/add-taille
    controller: App\Controller\AjaxController::addTaille
    methods: POST

report:
    path: /commande/report
    controller: App\Controller\ProductReportController::index
